version: "2"
services:
  app:
    image: rtcert/vior:latest
    environment:
      - VIOR_PORT=8080
      - VIOR_ELASTIC_URL=http://elastic:9200
    ports:
      - "10000:8080"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false

  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.3
    environment:
      - ELASTICSEARCH_URL=http://elastic:9200
    ports:
      - "5601:5601"
